server.port: 8083
spring.application.name: @application.name@
spring.profiles.active: dev

spring.mvc.favicon.enabled: false

spring.mvc.dispatch-options-request: true
logging.level.com.xw.it.sso.mapper: debug

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

spring.datasource.master.driverClassName: com.mysql.jdbc.Driver
spring.datasource.master.url: jdbc:mysql://wangyulin-test-host:3306/test?useUnicode=true&characterEncoding=UTF-8
spring.datasource.master.username : root
spring.datasource.master.password : 123456
spring.datasource.master.maxActive : 20
spring.datasource.master.minIdle : 5
spring.datasource.master.maxIdle : 20
spring.datasource.master.test-on-borrow : true
spring.datasource.master.dialect : mysql
spring.datasource.master.testOnBorrow : true

spring.datasource.slave.driverClassName : com.mysql.jdbc.Driver
spring.datasource.slave.url : jdbc:mysql://wangyulin-test-host:3306/test?useUnicode=true&characterEncoding=UTF-8
spring.datasource.slave.username : root
spring.datasource.slave.password : 123456
spring.datasource.slave.maxActive : 20
spring.datasource.slave.minIdle : 5
spring.datasource.slave.maxIdle : 20
spring.datasource.slave.test-on-borrow : true
spring.datasource.slave.dialect : mysql
spring.datasource.slave.testOnBorrow : true

PRODUCT_MODE : true